xebia-functional/books-store-training

Project/main/src/Main.java
=> Add main project

src/Main/Book.java, src/Main/Bookstore.java, src/Main/User.java, src/Main/libreria.java
=> Create Bookstore class

src/test/java/com/xebia/testBookstoreSuite.java
This PR create a test for the service Bookstore.
Refers to issue:  #22
=> Add Bookstore getters-setters test

.github/workflows/pull-request-build.yml
Added a GitHub action for PR checks.
=> 28 - Create GitHub action for check build

src/main/java/com/xebia/services/Bookstore.java
This PR creates the methods related to the object 'User' inside the 'Bookstore':
- addUser
- removeUser
- listUsers
PR for the issue #17
=> Methods related to 'User'

src/main/java/com/xebia/services/Bookstore.java
This PR creates the methods related to the service 'Bookstore':
-requestBook
-recordDate
-returnBook
-listBorrowed
PR for the issue #19
=> Methods related to Bookstore

.github/workflows/pull-request-build.yml
Updated PR action check to add tests check.
PR for issue #35
=> Create GitHub action for check test

src/main/java/com/xebia/models/User.java
This PR modifies the 'User' model to adjust the new code changes
PR -> #45
=> New User Model

src/main/java/com/xebia/models/Book.java, src/main/java/com/xebia/services/Bookstore.java
=> New Book Model

src/main/java/com/xebia/services/UserService.java
Creates the interface 'UserService' for future implementations
PR -> #46
=> Create UserService interface

src/main/java/com/xebia/services/Book/BookService.java
=> Create BookService interface

src/main/java/com/xebia/services/Book/BookServiceImpl.java
=> Create BookService imp

src/main/java/com/xebia/services/Book/BookServiceImpl.java, src/test/java/com/xebia/testBookServiceSuite.java
=> Create test for BookService

src/main/java/com/xebia/models/Book.java, src/main/java/com/xebia/services/Book/BookService.java, src/main/java/com/xebia/services/Book/BookServiceImpl.java, src/test/java/com/xebia/testBookServiceSuite.java
=> Update Book model and implementation

src/main/java/com/xebia/models/Register.java, src/main/java/com/xebia/services/Register/RegisterService.java, src/main/java/com/xebia/services/Register/RegisterServiceImp.java, src/test/java/com/xebia/TestBookServiceSuite.java, src/test/java/com/xebia/TestRegisterServiceSuite.java, src/test/java/com/xebia/TestUserServiceSuite.java
=> Create model Register

src/main/java/com/xebia/services/Register/RegisterService.java
PR -> #72 
This interface contains the following methods:
- addRegister
- removeRegister
- searchRegisterByUser
- searchRegisterByBook
- listRegistered
=> 72 register service

src/main/java/com/xebia/services/Bookstore/BookstoreService.java
=> Create BookstoreService interface

src/test/java/com/xebia/TestRegisterServiceSuite.java
=> 74 register service suite

src/main/java/com/xebia/models/Book.java, src/main/java/com/xebia/services/Book/BookService.java, src/main/java/com/xebia/services/Book/BookServiceImpl.java, src/main/java/com/xebia/services/Bookstore/BookstoreService.java, src/main/java/com/xebia/services/Bookstore/BookstoreServiceImp.java, src/test/java/com/xebia/TestBookServiceSuite.java
=> Create bookstore implementation

src/main/java/com/xebia/services/Book/BookService.java, src/main/java/com/xebia/services/Book/BookServiceImpl.java, src/test/java/com/xebia/TestBookServiceSuite.java
=> Update searchByAuthor method

build.gradle.kts, docker-compose.yml, gradle/libs.versions.toml, src/main/java/com/xebia/migrations/FlywayMigration.java
=> Add flyway migration

src/main/java/com/xebia/models/Register.java, src/main/java/com/xebia/services/Register/RegisterService.java, src/main/java/com/xebia/services/Register/RegisterServiceDBImpl.java, src/main/java/com/xebia/services/Register/RegisterServiceImp.java, src/test/java/com/xebia/TestBookstoreServiceSuite.java, src/test/java/com/xebia/register/TestRegisterServiceDBSuite.java, src/test/java/com/xebia/register/TestRegisterServiceSuite.java
=> Create RegisterService DB implementation
